=begin
#COUNTER_SUSHI5_0 API

#The COUNTER_SUSHI5_0 API represents a RESTful implementation of SUSHI automation intended to return COUNTER Release 5 reports and snippets of COUNTER usage in JSON format

OpenAPI spec version: 1.0.0
Contact: nisohq@niso.org
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 1.0.16

=end

require "uri"

module SwaggerClient
  class DefaultApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # 
    # This resource returns the current status of the reporting service supported by this API.
    # @param customer_id Identifies the customer to provide report data for.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the report data is being requested for.  This can be omitted if the service provides report data for only one platform.
    # @return [Array<SUSHIServiceStatus>]
    def get_api_status(customer_id, opts = {})
      data, _status_code, _headers = get_api_status_with_http_info(customer_id, opts)
      return data
    end

    # 
    # This resource returns the current status of the reporting service supported by this API.
    # @param customer_id Identifies the customer to provide report data for.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the report data is being requested for.  This can be omitted if the service provides report data for only one platform.
    # @return [Array<(Array<SUSHIServiceStatus>, Fixnum, Hash)>] Array<SUSHIServiceStatus> data, response status code and response headers
    def get_api_status_with_http_info(customer_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_api_status ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_api_status"
      end
      # resource path
      local_var_path = "/status"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<SUSHIServiceStatus>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_api_status\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns the list of consortium members related to a Customer_ID.
    # @param customer_id Identifies the customer to provide report data for.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the report data is being requested for.  This can be omitted if the service provides report data for only one platform.
    # @return [Array<SUSHIConsortiumMemberList>]
    def get_consortium_members(customer_id, opts = {})
      data, _status_code, _headers = get_consortium_members_with_http_info(customer_id, opts)
      return data
    end

    # 
    # This resource returns the list of consortium members related to a Customer_ID.
    # @param customer_id Identifies the customer to provide report data for.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the report data is being requested for.  This can be omitted if the service provides report data for only one platform.
    # @return [Array<(Array<SUSHIConsortiumMemberList>, Fixnum, Hash)>] Array<SUSHIConsortiumMemberList> data, response status code and response headers
    def get_consortium_members_with_http_info(customer_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_consortium_members ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_consortium_members"
      end
      # resource path
      local_var_path = "/members"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<SUSHIConsortiumMemberList>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_consortium_members\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns a list of reports supported by the API for a given application.
    # @param customer_id Identifies the customer to provide report data for.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform The name of the Platform the report data is being requested for.  This can be omitted if the service provides report data for only one platform.
    # @option opts [String] :search Keyword search filtered against report name. Allows for searching for a report by name.
    # @return [Array<SUSHIReportList>]
    def get_reports(customer_id, opts = {})
      data, _status_code, _headers = get_reports_with_http_info(customer_id, opts)
      return data
    end

    # 
    # This resource returns a list of reports supported by the API for a given application.
    # @param customer_id Identifies the customer to provide report data for.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform The name of the Platform the report data is being requested for.  This can be omitted if the service provides report data for only one platform.
    # @option opts [String] :search Keyword search filtered against report name. Allows for searching for a report by name.
    # @return [Array<(Array<SUSHIReportList>, Fixnum, Hash)>] Array<SUSHIReportList> data, response status code and response headers
    def get_reports_with_http_info(customer_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_reports ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_reports"
      end
      # resource path
      local_var_path = "/reports"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?
      query_params[:'search'] = opts[:'search'] if !opts[:'search'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<SUSHIReportList>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_reports\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns COUNTER 'Database Master Report' [DR]. A customizable report detailing activity by database that allows the user to apply filters and select other configuration options for the report.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @option opts [String] :database Name of a specific database usage is being requested for. If omitted, all databases on the platform with usage for the requested customer will be returned
    # @option opts [String] :metric_type A report filter. A list of Metric_Types to return. Specify multiple values by delimiting with a | character.  Omitting this parameter will return all metric_types with statistics. 
    # @option opts [String] :access_type A Report Filter. A list of Access_Types to return delimited with a | character.
    # @option opts [String] :access_method A Report Filter. A list of Access_Methods to return delimited with a | character.
    # @option opts [String] :yop A Report Filter. A list or range of years of publication to return in response in format of yyyy|yyyy|yyyy-yyyy. Note that 0001 &#x3D; unknown and 9999 &#x3D; articles in press
    # @option opts [String] :attributes_to_show A Report Attribute. A list of attributes to include as separate elements in response (usage will be broken out by attribute values).  Multiple attribute names are delimited with a | character. Options include Access_Type, Access_Method and YOP. When fields are included usage will be presented for each value of that field (with usage) otherwise usage will be rolled up for all values of a given field.
    # @option opts [String] :granularity Optional Report Attribute. Include this parameter to allow usage to be retrieved with a granularity of &#39;month&#39; (default if omitted), &#39;year&#39; or &#39;totals&#39;
    # @return [COUNTERDatabaseReport]
    def get_reports_d_rx(customer_id, begin_date, end_date, opts = {})
      data, _status_code, _headers = get_reports_d_rx_with_http_info(customer_id, begin_date, end_date, opts)
      return data
    end

    # 
    # This resource returns COUNTER &#39;Database Master Report&#39; [DR]. A customizable report detailing activity by database that allows the user to apply filters and select other configuration options for the report.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @option opts [String] :database Name of a specific database usage is being requested for. If omitted, all databases on the platform with usage for the requested customer will be returned
    # @option opts [String] :metric_type A report filter. A list of Metric_Types to return. Specify multiple values by delimiting with a | character.  Omitting this parameter will return all metric_types with statistics. 
    # @option opts [String] :access_type A Report Filter. A list of Access_Types to return delimited with a | character.
    # @option opts [String] :access_method A Report Filter. A list of Access_Methods to return delimited with a | character.
    # @option opts [String] :yop A Report Filter. A list or range of years of publication to return in response in format of yyyy|yyyy|yyyy-yyyy. Note that 0001 &#x3D; unknown and 9999 &#x3D; articles in press
    # @option opts [String] :attributes_to_show A Report Attribute. A list of attributes to include as separate elements in response (usage will be broken out by attribute values).  Multiple attribute names are delimited with a | character. Options include Access_Type, Access_Method and YOP. When fields are included usage will be presented for each value of that field (with usage) otherwise usage will be rolled up for all values of a given field.
    # @option opts [String] :granularity Optional Report Attribute. Include this parameter to allow usage to be retrieved with a granularity of &#39;month&#39; (default if omitted), &#39;year&#39; or &#39;totals&#39;
    # @return [Array<(COUNTERDatabaseReport, Fixnum, Hash)>] COUNTERDatabaseReport data, response status code and response headers
    def get_reports_d_rx_with_http_info(customer_id, begin_date, end_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_reports_d_rx ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_reports_d_rx"
      end
      # verify the required parameter 'begin_date' is set
      if @api_client.config.client_side_validation && begin_date.nil?
        fail ArgumentError, "Missing the required parameter 'begin_date' when calling DefaultApi.get_reports_d_rx"
      end
      # verify the required parameter 'end_date' is set
      if @api_client.config.client_side_validation && end_date.nil?
        fail ArgumentError, "Missing the required parameter 'end_date' when calling DefaultApi.get_reports_d_rx"
      end
      if @api_client.config.client_side_validation && opts[:'granularity'] && !['month', 'totals'].include?(opts[:'granularity'])
        fail ArgumentError, 'invalid value for "granularity", must be one of month, totals'
      end
      # resource path
      local_var_path = "/reports/dr"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'begin_date'] = begin_date
      query_params[:'end_date'] = end_date
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?
      query_params[:'database'] = opts[:'database'] if !opts[:'database'].nil?
      query_params[:'metric_type'] = opts[:'metric_type'] if !opts[:'metric_type'].nil?
      query_params[:'access_type'] = opts[:'access_type'] if !opts[:'access_type'].nil?
      query_params[:'access_method'] = opts[:'access_method'] if !opts[:'access_method'].nil?
      query_params[:'yop'] = opts[:'yop'] if !opts[:'yop'].nil?
      query_params[:'attributes_to_show'] = opts[:'attributes_to_show'] if !opts[:'attributes_to_show'].nil?
      query_params[:'granularity'] = opts[:'granularity'] if !opts[:'granularity'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'COUNTERDatabaseReport')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_reports_d_rx\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns COUNTER 'Database Search and Item Usage' [DR_D1], a Standard View of Database Master Report. Reports on key search and request metrics needed to evaluate a database.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [COUNTERDatabaseReport]
    def get_reports_dr1(customer_id, begin_date, end_date, opts = {})
      data, _status_code, _headers = get_reports_dr1_with_http_info(customer_id, begin_date, end_date, opts)
      return data
    end

    # 
    # This resource returns COUNTER &#39;Database Search and Item Usage&#39; [DR_D1], a Standard View of Database Master Report. Reports on key search and request metrics needed to evaluate a database.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [Array<(COUNTERDatabaseReport, Fixnum, Hash)>] COUNTERDatabaseReport data, response status code and response headers
    def get_reports_dr1_with_http_info(customer_id, begin_date, end_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_reports_dr1 ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_reports_dr1"
      end
      # verify the required parameter 'begin_date' is set
      if @api_client.config.client_side_validation && begin_date.nil?
        fail ArgumentError, "Missing the required parameter 'begin_date' when calling DefaultApi.get_reports_dr1"
      end
      # verify the required parameter 'end_date' is set
      if @api_client.config.client_side_validation && end_date.nil?
        fail ArgumentError, "Missing the required parameter 'end_date' when calling DefaultApi.get_reports_dr1"
      end
      # resource path
      local_var_path = "/reports/dr_d1"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'begin_date'] = begin_date
      query_params[:'end_date'] = end_date
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'COUNTERDatabaseReport')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_reports_dr1\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns COUNTER 'Database Access Denied' [DR_D2], a Standard View of Database Master Report. Reports on Access Denied activity for databases where users were denied access because simultaneous use licenses were exceeded or their institution did not have a license for the database.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [COUNTERDatabaseReport]
    def get_reports_dr2(customer_id, begin_date, end_date, opts = {})
      data, _status_code, _headers = get_reports_dr2_with_http_info(customer_id, begin_date, end_date, opts)
      return data
    end

    # 
    # This resource returns COUNTER &#39;Database Access Denied&#39; [DR_D2], a Standard View of Database Master Report. Reports on Access Denied activity for databases where users were denied access because simultaneous use licenses were exceeded or their institution did not have a license for the database.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [Array<(COUNTERDatabaseReport, Fixnum, Hash)>] COUNTERDatabaseReport data, response status code and response headers
    def get_reports_dr2_with_http_info(customer_id, begin_date, end_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_reports_dr2 ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_reports_dr2"
      end
      # verify the required parameter 'begin_date' is set
      if @api_client.config.client_side_validation && begin_date.nil?
        fail ArgumentError, "Missing the required parameter 'begin_date' when calling DefaultApi.get_reports_dr2"
      end
      # verify the required parameter 'end_date' is set
      if @api_client.config.client_side_validation && end_date.nil?
        fail ArgumentError, "Missing the required parameter 'end_date' when calling DefaultApi.get_reports_dr2"
      end
      # resource path
      local_var_path = "/reports/dr_d2"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'begin_date'] = begin_date
      query_params[:'end_date'] = end_date
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'COUNTERDatabaseReport')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_reports_dr2\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns COUNTER 'Item Master Report'  [IR].
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @option opts [String] :item_id Optional Report Filter. Identifier of a specific item usage is being requested for.  If omitted, all items on the platform with usage for the requested customer will be returned
    # @option opts [String] :item_contributor Optional Report Filter. Identifier of a specific contributor (i.e. author) usage is being requested for.  If omitted, all items on the platform with usage for the requested customer will be returned
    # @option opts [String] :metric_type Optional Report Filter. A list of Metric_Types to return usage for.  Use | character to delimit multiple values. Omit this parameter to include all metric_types with statistics.
    # @option opts [String] :data_type Optional Report Filter. A list of Data_Types to return usage for.  Use | character to delimit multiple values. Omit this parameter to include all Data_Types with statistics. 
    # @option opts [String] :section_type Optional Report Filter.  A list of Section_Types to return usage for.  Use | character to delimit multiple values. Omit this parameter to include all Section_Types with statistics.
    # @option opts [String] :yop Optional Report Filter. A list or range of years of publication to return in response in format of yyyy|yyyy|yyyy-yyyy. Note that 0001 &#x3D; unknown and 9999 &#x3D; articles in press
    # @option opts [String] :access_type Optional Report Filter. A list of Access_Types to return usage for -- delimited with a | character.
    # @option opts [String] :access_method Optional Report Filter. A list of Access_Methods to return usage for --  delimited with a | character.
    # @option opts [String] :attributes_to_show Optional Report Attribute. A list of attributes to include as separate elements in response (usage will be broken out by attribute values).  Multiple attribute names are delimited with a | character. Options include Access_Type, Access_Method and YOP. When fields are  included usage will be presented for each value of that field (with usage) otherwise usage will be rolled up for all values of a given field.
    # @option opts [String] :include_item_components Optional Report Attribute. Include this parameter to include ItemComponent details in the report. Omitting the parameter will exclude the ItemComponent elements.
    # @option opts [String] :granularity Optional Report Attribute. Include this parameter to allow usage to be retrieved with a granularity of &#39;month&#39; (default if omitted), &#39;year&#39; or &#39;totals&#39;
    # @return [COUNTERItemReport]
    def get_reports_ir(customer_id, begin_date, end_date, opts = {})
      data, _status_code, _headers = get_reports_ir_with_http_info(customer_id, begin_date, end_date, opts)
      return data
    end

    # 
    # This resource returns COUNTER &#39;Item Master Report&#39;  [IR].
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @option opts [String] :item_id Optional Report Filter. Identifier of a specific item usage is being requested for.  If omitted, all items on the platform with usage for the requested customer will be returned
    # @option opts [String] :item_contributor Optional Report Filter. Identifier of a specific contributor (i.e. author) usage is being requested for.  If omitted, all items on the platform with usage for the requested customer will be returned
    # @option opts [String] :metric_type Optional Report Filter. A list of Metric_Types to return usage for.  Use | character to delimit multiple values. Omit this parameter to include all metric_types with statistics.
    # @option opts [String] :data_type Optional Report Filter. A list of Data_Types to return usage for.  Use | character to delimit multiple values. Omit this parameter to include all Data_Types with statistics. 
    # @option opts [String] :section_type Optional Report Filter.  A list of Section_Types to return usage for.  Use | character to delimit multiple values. Omit this parameter to include all Section_Types with statistics.
    # @option opts [String] :yop Optional Report Filter. A list or range of years of publication to return in response in format of yyyy|yyyy|yyyy-yyyy. Note that 0001 &#x3D; unknown and 9999 &#x3D; articles in press
    # @option opts [String] :access_type Optional Report Filter. A list of Access_Types to return usage for -- delimited with a | character.
    # @option opts [String] :access_method Optional Report Filter. A list of Access_Methods to return usage for --  delimited with a | character.
    # @option opts [String] :attributes_to_show Optional Report Attribute. A list of attributes to include as separate elements in response (usage will be broken out by attribute values).  Multiple attribute names are delimited with a | character. Options include Access_Type, Access_Method and YOP. When fields are  included usage will be presented for each value of that field (with usage) otherwise usage will be rolled up for all values of a given field.
    # @option opts [String] :include_item_components Optional Report Attribute. Include this parameter to include ItemComponent details in the report. Omitting the parameter will exclude the ItemComponent elements.
    # @option opts [String] :granularity Optional Report Attribute. Include this parameter to allow usage to be retrieved with a granularity of &#39;month&#39; (default if omitted), &#39;year&#39; or &#39;totals&#39;
    # @return [Array<(COUNTERItemReport, Fixnum, Hash)>] COUNTERItemReport data, response status code and response headers
    def get_reports_ir_with_http_info(customer_id, begin_date, end_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_reports_ir ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_reports_ir"
      end
      # verify the required parameter 'begin_date' is set
      if @api_client.config.client_side_validation && begin_date.nil?
        fail ArgumentError, "Missing the required parameter 'begin_date' when calling DefaultApi.get_reports_ir"
      end
      # verify the required parameter 'end_date' is set
      if @api_client.config.client_side_validation && end_date.nil?
        fail ArgumentError, "Missing the required parameter 'end_date' when calling DefaultApi.get_reports_ir"
      end
      if @api_client.config.client_side_validation && opts[:'granularity'] && !['month', 'totals'].include?(opts[:'granularity'])
        fail ArgumentError, 'invalid value for "granularity", must be one of month, totals'
      end
      # resource path
      local_var_path = "/reports/ir"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'begin_date'] = begin_date
      query_params[:'end_date'] = end_date
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?
      query_params[:'item_id'] = opts[:'item_id'] if !opts[:'item_id'].nil?
      query_params[:'item_contributor'] = opts[:'item_contributor'] if !opts[:'item_contributor'].nil?
      query_params[:'metric_type'] = opts[:'metric_type'] if !opts[:'metric_type'].nil?
      query_params[:'data_type'] = opts[:'data_type'] if !opts[:'data_type'].nil?
      query_params[:'section_type'] = opts[:'section_type'] if !opts[:'section_type'].nil?
      query_params[:'yop'] = opts[:'yop'] if !opts[:'yop'].nil?
      query_params[:'access_type'] = opts[:'access_type'] if !opts[:'access_type'].nil?
      query_params[:'access_method'] = opts[:'access_method'] if !opts[:'access_method'].nil?
      query_params[:'attributes_to_show'] = opts[:'attributes_to_show'] if !opts[:'attributes_to_show'].nil?
      query_params[:'include_item_components'] = opts[:'include_item_components'] if !opts[:'include_item_components'].nil?
      query_params[:'granularity'] = opts[:'granularity'] if !opts[:'granularity'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'COUNTERItemReport')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_reports_ir\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns 'Journal Article Requests' [IR_A1], a Standard View of Item Master Report. Reports on journal article requests at the article level. This report is limited to content with a Data_Type of Journal; Section_Type of Article and metric types of Total_Item_Requests and Unique_Item_Requests.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [COUNTERItemReport]
    def get_reports_ira1(customer_id, begin_date, end_date, opts = {})
      data, _status_code, _headers = get_reports_ira1_with_http_info(customer_id, begin_date, end_date, opts)
      return data
    end

    # 
    # This resource returns &#39;Journal Article Requests&#39; [IR_A1], a Standard View of Item Master Report. Reports on journal article requests at the article level. This report is limited to content with a Data_Type of Journal; Section_Type of Article and metric types of Total_Item_Requests and Unique_Item_Requests.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [Array<(COUNTERItemReport, Fixnum, Hash)>] COUNTERItemReport data, response status code and response headers
    def get_reports_ira1_with_http_info(customer_id, begin_date, end_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_reports_ira1 ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_reports_ira1"
      end
      # verify the required parameter 'begin_date' is set
      if @api_client.config.client_side_validation && begin_date.nil?
        fail ArgumentError, "Missing the required parameter 'begin_date' when calling DefaultApi.get_reports_ira1"
      end
      # verify the required parameter 'end_date' is set
      if @api_client.config.client_side_validation && end_date.nil?
        fail ArgumentError, "Missing the required parameter 'end_date' when calling DefaultApi.get_reports_ira1"
      end
      # resource path
      local_var_path = "/reports/ir_a1"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'begin_date'] = begin_date
      query_params[:'end_date'] = end_date
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'COUNTERItemReport')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_reports_ira1\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns 'Multimedia Item Requests' [IR_M1], a Standard View of Item Master Report. Reports on multimedia requests at the item level.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [COUNTERItemReport]
    def get_reports_irm1(customer_id, begin_date, end_date, opts = {})
      data, _status_code, _headers = get_reports_irm1_with_http_info(customer_id, begin_date, end_date, opts)
      return data
    end

    # 
    # This resource returns &#39;Multimedia Item Requests&#39; [IR_M1], a Standard View of Item Master Report. Reports on multimedia requests at the item level.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [Array<(COUNTERItemReport, Fixnum, Hash)>] COUNTERItemReport data, response status code and response headers
    def get_reports_irm1_with_http_info(customer_id, begin_date, end_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_reports_irm1 ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_reports_irm1"
      end
      # verify the required parameter 'begin_date' is set
      if @api_client.config.client_side_validation && begin_date.nil?
        fail ArgumentError, "Missing the required parameter 'begin_date' when calling DefaultApi.get_reports_irm1"
      end
      # verify the required parameter 'end_date' is set
      if @api_client.config.client_side_validation && end_date.nil?
        fail ArgumentError, "Missing the required parameter 'end_date' when calling DefaultApi.get_reports_irm1"
      end
      # resource path
      local_var_path = "/reports/ir_m1"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'begin_date'] = begin_date
      query_params[:'end_date'] = end_date
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'COUNTERItemReport')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_reports_irm1\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns COUNTER 'Platform Master Report' [PR]. A customizable report summarizing activity across a provider’s platforms that allows the user to apply filters and select other configuration options for the report.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @option opts [String] :metric_type Optional Report Filter. A list of Metric_Types to return. Specify multiple values by delimiting with a | character.  Omitting this parameter will return all metric_types with statistics. 
    # @option opts [String] :access_type Optional Report Filter. A list of Access_Types to return delimited with a | character. Omitting this parameter will return all access_types with statistics.
    # @option opts [String] :access_method Optional Report Filter. A list of Access_Methods to return delimited with a | character. Omitting this parameter will return all access_methods with statistics.
    # @option opts [String] :yop Optional Report Filter. A list or range of years of publication to return in response in format of yyyy|yyyy|yyyy-yyyy. Note that 0001 &#x3D; unknown and 9999 &#x3D; articles in press.
    # @option opts [String] :attributes_to_show Optional Report Attribute. A list of attributes to include as separate elements in response (usage will be broken out by attribute values).  Multiple attribute names are delimited with a | character. Options include Access_Type, Access_Method and YOP. When fields are included usage will be presented for each value of that field (with     usage) otherwise usage will be rolled up for all values of a given field.
    # @option opts [String] :granularity Optional Report Attribute. Include this parameter to allow usage to be retrieved with a granularity of &#39;month&#39; (default if omitted), &#39;year&#39; or &#39;totals&#39;
    # @return [COUNTERPlatformReport]
    def get_reports_pr(customer_id, begin_date, end_date, opts = {})
      data, _status_code, _headers = get_reports_pr_with_http_info(customer_id, begin_date, end_date, opts)
      return data
    end

    # 
    # This resource returns COUNTER &#39;Platform Master Report&#39; [PR]. A customizable report summarizing activity across a provider’s platforms that allows the user to apply filters and select other configuration options for the report.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @option opts [String] :metric_type Optional Report Filter. A list of Metric_Types to return. Specify multiple values by delimiting with a | character.  Omitting this parameter will return all metric_types with statistics. 
    # @option opts [String] :access_type Optional Report Filter. A list of Access_Types to return delimited with a | character. Omitting this parameter will return all access_types with statistics.
    # @option opts [String] :access_method Optional Report Filter. A list of Access_Methods to return delimited with a | character. Omitting this parameter will return all access_methods with statistics.
    # @option opts [String] :yop Optional Report Filter. A list or range of years of publication to return in response in format of yyyy|yyyy|yyyy-yyyy. Note that 0001 &#x3D; unknown and 9999 &#x3D; articles in press.
    # @option opts [String] :attributes_to_show Optional Report Attribute. A list of attributes to include as separate elements in response (usage will be broken out by attribute values).  Multiple attribute names are delimited with a | character. Options include Access_Type, Access_Method and YOP. When fields are included usage will be presented for each value of that field (with     usage) otherwise usage will be rolled up for all values of a given field.
    # @option opts [String] :granularity Optional Report Attribute. Include this parameter to allow usage to be retrieved with a granularity of &#39;month&#39; (default if omitted), &#39;year&#39; or &#39;totals&#39;
    # @return [Array<(COUNTERPlatformReport, Fixnum, Hash)>] COUNTERPlatformReport data, response status code and response headers
    def get_reports_pr_with_http_info(customer_id, begin_date, end_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_reports_pr ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_reports_pr"
      end
      # verify the required parameter 'begin_date' is set
      if @api_client.config.client_side_validation && begin_date.nil?
        fail ArgumentError, "Missing the required parameter 'begin_date' when calling DefaultApi.get_reports_pr"
      end
      # verify the required parameter 'end_date' is set
      if @api_client.config.client_side_validation && end_date.nil?
        fail ArgumentError, "Missing the required parameter 'end_date' when calling DefaultApi.get_reports_pr"
      end
      if @api_client.config.client_side_validation && opts[:'granularity'] && !['month', 'totals'].include?(opts[:'granularity'])
        fail ArgumentError, 'invalid value for "granularity", must be one of month, totals'
      end
      # resource path
      local_var_path = "/reports/pr"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'begin_date'] = begin_date
      query_params[:'end_date'] = end_date
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?
      query_params[:'metric_type'] = opts[:'metric_type'] if !opts[:'metric_type'].nil?
      query_params[:'access_type'] = opts[:'access_type'] if !opts[:'access_type'].nil?
      query_params[:'access_method'] = opts[:'access_method'] if !opts[:'access_method'].nil?
      query_params[:'yop'] = opts[:'yop'] if !opts[:'yop'].nil?
      query_params[:'attributes_to_show'] = opts[:'attributes_to_show'] if !opts[:'attributes_to_show'].nil?
      query_params[:'granularity'] = opts[:'granularity'] if !opts[:'granularity'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'COUNTERPlatformReport')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_reports_pr\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns COUNTER 'Platform Usage' [pr_p1]. This is a Standard View of the Package Master Report that presents usage for the overall Platform broken down by Metric_Type.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [COUNTERPlatformReport]
    def get_reports_pr1(customer_id, begin_date, end_date, opts = {})
      data, _status_code, _headers = get_reports_pr1_with_http_info(customer_id, begin_date, end_date, opts)
      return data
    end

    # 
    # This resource returns COUNTER &#39;Platform Usage&#39; [pr_p1]. This is a Standard View of the Package Master Report that presents usage for the overall Platform broken down by Metric_Type.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [Array<(COUNTERPlatformReport, Fixnum, Hash)>] COUNTERPlatformReport data, response status code and response headers
    def get_reports_pr1_with_http_info(customer_id, begin_date, end_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_reports_pr1 ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_reports_pr1"
      end
      # verify the required parameter 'begin_date' is set
      if @api_client.config.client_side_validation && begin_date.nil?
        fail ArgumentError, "Missing the required parameter 'begin_date' when calling DefaultApi.get_reports_pr1"
      end
      # verify the required parameter 'end_date' is set
      if @api_client.config.client_side_validation && end_date.nil?
        fail ArgumentError, "Missing the required parameter 'end_date' when calling DefaultApi.get_reports_pr1"
      end
      # resource path
      local_var_path = "/reports/pr_p1"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'begin_date'] = begin_date
      query_params[:'end_date'] = end_date
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'COUNTERPlatformReport')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_reports_pr1\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns COUNTER 'Title Master Report' [TR]. A customizable report detailing activity at the title level (journal, book, etc.) that allows the user to apply filters and select other configuration options for the report.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @option opts [String] :item_id Identifier of a specific title usage is being requested for.  If omitted, all titles on the platform with usage for the requested customer will be returned
    # @option opts [String] :metric_type A Report Filter. A list of Metric_Types to return usage for.  Use | character to delimit multiple values. Omit this parameter to include all metric_types with statistics.
    # @option opts [String] :data_type A Report Filter. A list of Data_Types to return usage for.  Use | character to delimit multiple values. Omit this parameter to include all Data_Types with statistics. 
    # @option opts [String] :section_type A Report Filter. A list of Data_Types to return usage for.  Use | character to delimit multiple values. Omit this parameter to include all Section_Types with statistics.
    # @option opts [String] :yop A Report Filter. A list or range of years of publication to return in response in format of yyyy|yyyy|yyyy-yyyy. Note that 0001 &#x3D; unknown and 9999 &#x3D; articles in press
    # @option opts [String] :access_type A Report Filter. A list of Access_Types to return usage for -- delimited with a | character.
    # @option opts [String] :access_method A Report Filter. A list of Access_Methods to return usage for --  delimited with a | character.
    # @option opts [String] :attributes_to_show A Report Attribute. A list of attributes to include as separate elements in response (usage will be broken out by attribute values).  Multiple attribute names are delimited with a | character.  Options include Access_Type, Access_Method and YOP. When fields are included usage will be presented for each value of that field (with usage) otherwise usage will be rolled up for all values of a given field.
    # @option opts [String] :granularity Optional Report Attribute. Include this parameter to allow usage to be retrieved with a granularity of &#39;month&#39; (default if omitted), &#39;year&#39; or &#39;totals&#39;
    # @return [COUNTERTitleReport]
    def get_reports_tr(customer_id, begin_date, end_date, opts = {})
      data, _status_code, _headers = get_reports_tr_with_http_info(customer_id, begin_date, end_date, opts)
      return data
    end

    # 
    # This resource returns COUNTER &#39;Title Master Report&#39; [TR]. A customizable report detailing activity at the title level (journal, book, etc.) that allows the user to apply filters and select other configuration options for the report.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @option opts [String] :item_id Identifier of a specific title usage is being requested for.  If omitted, all titles on the platform with usage for the requested customer will be returned
    # @option opts [String] :metric_type A Report Filter. A list of Metric_Types to return usage for.  Use | character to delimit multiple values. Omit this parameter to include all metric_types with statistics.
    # @option opts [String] :data_type A Report Filter. A list of Data_Types to return usage for.  Use | character to delimit multiple values. Omit this parameter to include all Data_Types with statistics. 
    # @option opts [String] :section_type A Report Filter. A list of Data_Types to return usage for.  Use | character to delimit multiple values. Omit this parameter to include all Section_Types with statistics.
    # @option opts [String] :yop A Report Filter. A list or range of years of publication to return in response in format of yyyy|yyyy|yyyy-yyyy. Note that 0001 &#x3D; unknown and 9999 &#x3D; articles in press
    # @option opts [String] :access_type A Report Filter. A list of Access_Types to return usage for -- delimited with a | character.
    # @option opts [String] :access_method A Report Filter. A list of Access_Methods to return usage for --  delimited with a | character.
    # @option opts [String] :attributes_to_show A Report Attribute. A list of attributes to include as separate elements in response (usage will be broken out by attribute values).  Multiple attribute names are delimited with a | character.  Options include Access_Type, Access_Method and YOP. When fields are included usage will be presented for each value of that field (with usage) otherwise usage will be rolled up for all values of a given field.
    # @option opts [String] :granularity Optional Report Attribute. Include this parameter to allow usage to be retrieved with a granularity of &#39;month&#39; (default if omitted), &#39;year&#39; or &#39;totals&#39;
    # @return [Array<(COUNTERTitleReport, Fixnum, Hash)>] COUNTERTitleReport data, response status code and response headers
    def get_reports_tr_with_http_info(customer_id, begin_date, end_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_reports_tr ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_reports_tr"
      end
      # verify the required parameter 'begin_date' is set
      if @api_client.config.client_side_validation && begin_date.nil?
        fail ArgumentError, "Missing the required parameter 'begin_date' when calling DefaultApi.get_reports_tr"
      end
      # verify the required parameter 'end_date' is set
      if @api_client.config.client_side_validation && end_date.nil?
        fail ArgumentError, "Missing the required parameter 'end_date' when calling DefaultApi.get_reports_tr"
      end
      if @api_client.config.client_side_validation && opts[:'granularity'] && !['month', 'totals'].include?(opts[:'granularity'])
        fail ArgumentError, 'invalid value for "granularity", must be one of month, totals'
      end
      # resource path
      local_var_path = "/reports/tr"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'begin_date'] = begin_date
      query_params[:'end_date'] = end_date
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?
      query_params[:'item_id'] = opts[:'item_id'] if !opts[:'item_id'].nil?
      query_params[:'metric_type'] = opts[:'metric_type'] if !opts[:'metric_type'].nil?
      query_params[:'data_type'] = opts[:'data_type'] if !opts[:'data_type'].nil?
      query_params[:'section_type'] = opts[:'section_type'] if !opts[:'section_type'].nil?
      query_params[:'yop'] = opts[:'yop'] if !opts[:'yop'].nil?
      query_params[:'access_type'] = opts[:'access_type'] if !opts[:'access_type'].nil?
      query_params[:'access_method'] = opts[:'access_method'] if !opts[:'access_method'].nil?
      query_params[:'attributes_to_show'] = opts[:'attributes_to_show'] if !opts[:'attributes_to_show'].nil?
      query_params[:'granularity'] = opts[:'granularity'] if !opts[:'granularity'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'COUNTERTitleReport')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_reports_tr\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns COUNTER Book Requests (Excluding OA_Gold) [TR_B1], a Standard View of Title Master Report. Reports on full text activity for non-Gold Open Access books as “Total_Item_Requests” and “Unique_Title_Requests”.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [COUNTERTitleReport]
    def get_reports_trb1(customer_id, begin_date, end_date, opts = {})
      data, _status_code, _headers = get_reports_trb1_with_http_info(customer_id, begin_date, end_date, opts)
      return data
    end

    # 
    # This resource returns COUNTER Book Requests (Excluding OA_Gold) [TR_B1], a Standard View of Title Master Report. Reports on full text activity for non-Gold Open Access books as “Total_Item_Requests” and “Unique_Title_Requests”.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [Array<(COUNTERTitleReport, Fixnum, Hash)>] COUNTERTitleReport data, response status code and response headers
    def get_reports_trb1_with_http_info(customer_id, begin_date, end_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_reports_trb1 ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_reports_trb1"
      end
      # verify the required parameter 'begin_date' is set
      if @api_client.config.client_side_validation && begin_date.nil?
        fail ArgumentError, "Missing the required parameter 'begin_date' when calling DefaultApi.get_reports_trb1"
      end
      # verify the required parameter 'end_date' is set
      if @api_client.config.client_side_validation && end_date.nil?
        fail ArgumentError, "Missing the required parameter 'end_date' when calling DefaultApi.get_reports_trb1"
      end
      # resource path
      local_var_path = "/reports/tr_b1"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'begin_date'] = begin_date
      query_params[:'end_date'] = end_date
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'COUNTERTitleReport')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_reports_trb1\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns COUNTER 'Access Denied by Book'[TR_B2], a Standard View of Title Master Report. Reports on Access Denied activity for books where users were denied access because simultaneous use licenses were exceeded or their institution did not have a license for the book.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [COUNTERTitleReport]
    def get_reports_trb2(customer_id, begin_date, end_date, opts = {})
      data, _status_code, _headers = get_reports_trb2_with_http_info(customer_id, begin_date, end_date, opts)
      return data
    end

    # 
    # This resource returns COUNTER &#39;Access Denied by Book&#39;[TR_B2], a Standard View of Title Master Report. Reports on Access Denied activity for books where users were denied access because simultaneous use licenses were exceeded or their institution did not have a license for the book.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [Array<(COUNTERTitleReport, Fixnum, Hash)>] COUNTERTitleReport data, response status code and response headers
    def get_reports_trb2_with_http_info(customer_id, begin_date, end_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_reports_trb2 ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_reports_trb2"
      end
      # verify the required parameter 'begin_date' is set
      if @api_client.config.client_side_validation && begin_date.nil?
        fail ArgumentError, "Missing the required parameter 'begin_date' when calling DefaultApi.get_reports_trb2"
      end
      # verify the required parameter 'end_date' is set
      if @api_client.config.client_side_validation && end_date.nil?
        fail ArgumentError, "Missing the required parameter 'end_date' when calling DefaultApi.get_reports_trb2"
      end
      # resource path
      local_var_path = "/reports/tr_b2"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'begin_date'] = begin_date
      query_params[:'end_date'] = end_date
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'COUNTERTitleReport')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_reports_trb2\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns COUNTER 'Book Usage by Access Type' [TR_B3], a Standard View of Title Master Report. Reports on book usage showing all applicable metric types broken down by Access_Type.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [COUNTERTitleReport]
    def get_reports_trb3(customer_id, begin_date, end_date, opts = {})
      data, _status_code, _headers = get_reports_trb3_with_http_info(customer_id, begin_date, end_date, opts)
      return data
    end

    # 
    # This resource returns COUNTER &#39;Book Usage by Access Type&#39; [TR_B3], a Standard View of Title Master Report. Reports on book usage showing all applicable metric types broken down by Access_Type.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [Array<(COUNTERTitleReport, Fixnum, Hash)>] COUNTERTitleReport data, response status code and response headers
    def get_reports_trb3_with_http_info(customer_id, begin_date, end_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_reports_trb3 ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_reports_trb3"
      end
      # verify the required parameter 'begin_date' is set
      if @api_client.config.client_side_validation && begin_date.nil?
        fail ArgumentError, "Missing the required parameter 'begin_date' when calling DefaultApi.get_reports_trb3"
      end
      # verify the required parameter 'end_date' is set
      if @api_client.config.client_side_validation && end_date.nil?
        fail ArgumentError, "Missing the required parameter 'end_date' when calling DefaultApi.get_reports_trb3"
      end
      # resource path
      local_var_path = "/reports/tr_b3"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'begin_date'] = begin_date
      query_params[:'end_date'] = end_date
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'COUNTERTitleReport')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_reports_trb3\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns COUNTER 'Journal Requests (Excluding OA_Gold)' [TR_J1], a Standard View of Title Master Report. Reports on usage of non-Gold Open Access journal content as “Total_Item_Requests” and “Unique_Item_Requests”. 
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [COUNTERTitleReport]
    def get_reports_trj1(customer_id, begin_date, end_date, opts = {})
      data, _status_code, _headers = get_reports_trj1_with_http_info(customer_id, begin_date, end_date, opts)
      return data
    end

    # 
    # This resource returns COUNTER &#39;Journal Requests (Excluding OA_Gold)&#39; [TR_J1], a Standard View of Title Master Report. Reports on usage of non-Gold Open Access journal content as “Total_Item_Requests” and “Unique_Item_Requests”. 
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [Array<(COUNTERTitleReport, Fixnum, Hash)>] COUNTERTitleReport data, response status code and response headers
    def get_reports_trj1_with_http_info(customer_id, begin_date, end_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_reports_trj1 ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_reports_trj1"
      end
      # verify the required parameter 'begin_date' is set
      if @api_client.config.client_side_validation && begin_date.nil?
        fail ArgumentError, "Missing the required parameter 'begin_date' when calling DefaultApi.get_reports_trj1"
      end
      # verify the required parameter 'end_date' is set
      if @api_client.config.client_side_validation && end_date.nil?
        fail ArgumentError, "Missing the required parameter 'end_date' when calling DefaultApi.get_reports_trj1"
      end
      # resource path
      local_var_path = "/reports/tr_j1"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'begin_date'] = begin_date
      query_params[:'end_date'] = end_date
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'COUNTERTitleReport')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_reports_trj1\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns 'Access Denied by Journal' [TR_J2], a Standard View of Title Master Report. Reports on Access Denied activity for journal content where users were denied access because simultaneous use licenses were exceeded or their institution did not have a license for the title.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [COUNTERTitleReport]
    def get_reports_trj2(customer_id, begin_date, end_date, opts = {})
      data, _status_code, _headers = get_reports_trj2_with_http_info(customer_id, begin_date, end_date, opts)
      return data
    end

    # 
    # This resource returns &#39;Access Denied by Journal&#39; [TR_J2], a Standard View of Title Master Report. Reports on Access Denied activity for journal content where users were denied access because simultaneous use licenses were exceeded or their institution did not have a license for the title.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [Array<(COUNTERTitleReport, Fixnum, Hash)>] COUNTERTitleReport data, response status code and response headers
    def get_reports_trj2_with_http_info(customer_id, begin_date, end_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_reports_trj2 ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_reports_trj2"
      end
      # verify the required parameter 'begin_date' is set
      if @api_client.config.client_side_validation && begin_date.nil?
        fail ArgumentError, "Missing the required parameter 'begin_date' when calling DefaultApi.get_reports_trj2"
      end
      # verify the required parameter 'end_date' is set
      if @api_client.config.client_side_validation && end_date.nil?
        fail ArgumentError, "Missing the required parameter 'end_date' when calling DefaultApi.get_reports_trj2"
      end
      # resource path
      local_var_path = "/reports/tr_j2"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'begin_date'] = begin_date
      query_params[:'end_date'] = end_date
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'COUNTERTitleReport')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_reports_trj2\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns 'Journal Usage by Access Type ' [TR_J3], a Standard View of Title Master Report. Reports on usage of journal content for all metric types broken down by Access Type.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [COUNTERTitleReport]
    def get_reports_trj3(customer_id, begin_date, end_date, opts = {})
      data, _status_code, _headers = get_reports_trj3_with_http_info(customer_id, begin_date, end_date, opts)
      return data
    end

    # 
    # This resource returns &#39;Journal Usage by Access Type &#39; [TR_J3], a Standard View of Title Master Report. Reports on usage of journal content for all metric types broken down by Access Type.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [Array<(COUNTERTitleReport, Fixnum, Hash)>] COUNTERTitleReport data, response status code and response headers
    def get_reports_trj3_with_http_info(customer_id, begin_date, end_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_reports_trj3 ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_reports_trj3"
      end
      # verify the required parameter 'begin_date' is set
      if @api_client.config.client_side_validation && begin_date.nil?
        fail ArgumentError, "Missing the required parameter 'begin_date' when calling DefaultApi.get_reports_trj3"
      end
      # verify the required parameter 'end_date' is set
      if @api_client.config.client_side_validation && end_date.nil?
        fail ArgumentError, "Missing the required parameter 'end_date' when calling DefaultApi.get_reports_trj3"
      end
      # resource path
      local_var_path = "/reports/tr_j3"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'begin_date'] = begin_date
      query_params[:'end_date'] = end_date
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'COUNTERTitleReport')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_reports_trj3\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # This resource returns \"Journal Requests by YOP (Excluding OA_Gold)\" [TR_J4], a Standard View of Title Master Report. Breaks down the usage of non-Gold Open Access journal content by year of publication (YOP) providing counts for the metric types \"Total_Item_Requests\" and \"Unique_Item_Requests\".
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [COUNTERTitleReport]
    def get_reports_trj4(customer_id, begin_date, end_date, opts = {})
      data, _status_code, _headers = get_reports_trj4_with_http_info(customer_id, begin_date, end_date, opts)
      return data
    end

    # 
    # This resource returns \&quot;Journal Requests by YOP (Excluding OA_Gold)\&quot; [TR_J4], a Standard View of Title Master Report. Breaks down the usage of non-Gold Open Access journal content by year of publication (YOP) providing counts for the metric types \&quot;Total_Item_Requests\&quot; and \&quot;Unique_Item_Requests\&quot;.
    # @param customer_id Identifies the customer to provide usage for.
    # @param begin_date Usage start date in the form of yyyy-mm-dd or yyyy-mm.
    # @param end_date Usage end date in the form of yyyy-mm-dd or yyyy-mm.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :platform Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
    # @return [Array<(COUNTERTitleReport, Fixnum, Hash)>] COUNTERTitleReport data, response status code and response headers
    def get_reports_trj4_with_http_info(customer_id, begin_date, end_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DefaultApi.get_reports_trj4 ..."
      end
      # verify the required parameter 'customer_id' is set
      if @api_client.config.client_side_validation && customer_id.nil?
        fail ArgumentError, "Missing the required parameter 'customer_id' when calling DefaultApi.get_reports_trj4"
      end
      # verify the required parameter 'begin_date' is set
      if @api_client.config.client_side_validation && begin_date.nil?
        fail ArgumentError, "Missing the required parameter 'begin_date' when calling DefaultApi.get_reports_trj4"
      end
      # verify the required parameter 'end_date' is set
      if @api_client.config.client_side_validation && end_date.nil?
        fail ArgumentError, "Missing the required parameter 'end_date' when calling DefaultApi.get_reports_trj4"
      end
      # resource path
      local_var_path = "/reports/tr_j4"

      # query parameters
      query_params = {}
      query_params[:'customer_id'] = customer_id
      query_params[:'begin_date'] = begin_date
      query_params[:'end_date'] = end_date
      query_params[:'platform'] = opts[:'platform'] if !opts[:'platform'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apikey', 'requestor_id']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'COUNTERTitleReport')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DefaultApi#get_reports_trj4\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
