=begin
#COUNTER_SUSHI5_0 API

#The COUNTER_SUSHI5_0 API represents a RESTful implementation of SUSHI automation intended to return COUNTER Release 5 reports and snippets of COUNTER usage in JSON format

OpenAPI spec version: 1.0.0
Contact: nisohq@niso.org
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 1.0.16

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::COUNTERItemPerformanceInstance
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'COUNTERItemPerformanceInstance' do
  before do
    # run before each test
    @instance = SwaggerClient::COUNTERItemPerformanceInstance.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of COUNTERItemPerformanceInstance' do
    it 'should create an instance of COUNTERItemPerformanceInstance' do
      expect(@instance).to be_instance_of(SwaggerClient::COUNTERItemPerformanceInstance)
    end
  end
  describe 'test attribute "metric_type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Searches_Automated", "Searches_Federated", "Searches_Platform", "Searches_Regular", "Total_Item_Investigations", "Total_Item_Requests", "Unique_Item_Investigations", "Unique_Item_Requests", "Unique_Title_Investigations", "Unique_Title_Requests", "No_License", "Limit_Exceeded"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.metric_type = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "count"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

