=begin
#COUNTER_SUSHI5_0 API

#The COUNTER_SUSHI5_0 API represents a RESTful implementation of SUSHI automation intended to return COUNTER Release 5 reports and snippets of COUNTER usage in JSON format

OpenAPI spec version: 1.0.0
Contact: nisohq@niso.org
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 1.0.16

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/counter_database_report'
require 'swagger_client/models/counter_database_usage'
require 'swagger_client/models/counter_item_attributes'
require 'swagger_client/models/counter_item_component'
require 'swagger_client/models/counter_item_contributors'
require 'swagger_client/models/counter_item_dates'
require 'swagger_client/models/counter_item_identifiers'
require 'swagger_client/models/counter_item_parent'
require 'swagger_client/models/counter_item_performance'
require 'swagger_client/models/counter_item_performance_instance'
require 'swagger_client/models/counter_item_performance_period'
require 'swagger_client/models/counter_item_report'
require 'swagger_client/models/counter_item_usage'
require 'swagger_client/models/counter_platform_report'
require 'swagger_client/models/counter_platform_usage'
require 'swagger_client/models/counter_publisher_identifiers'
require 'swagger_client/models/counter_title_report'
require 'swagger_client/models/counter_title_usage'
require 'swagger_client/models/sushi_consortium_member_list'
require 'swagger_client/models/sushi_error_model'
require 'swagger_client/models/sushi_org_identifiers'
require 'swagger_client/models/sushi_report_header'
require 'swagger_client/models/sushi_report_header_report_attributes'
require 'swagger_client/models/sushi_report_header_report_filters'
require 'swagger_client/models/sushi_report_list'
require 'swagger_client/models/sushi_service_status'
require 'swagger_client/models/sushi_service_status_alerts'

# APIs
require 'swagger_client/api/default_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
